#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2020.nc 
